export { default as Layout } from './Layout/Layout';
export { default as Header } from './Header/Header';
export { default as HomeMain } from './Home/HomeMain';
export { default as AboutUsMain } from './AboutUs/AboutUsMain';
export { default as ServiseMain } from './Services/ServiseMain';
export { default as NewsMain } from './News/NewsMain';
export { default as PriceListMain } from './PriceList/PriceListMain';
export { default as ContactsMain } from './Сontacts/ContactsMain';
export { default as NotFound } from '../page/NotFound/NotFound';
export { default as Footer } from './Footer/Footer'
export { default as Finans } from '../components/Services/Finans/Finans';
export { default as Lawyer } from '../components/Services/Lawyer/Lawyer';
export { default as Management } from '../components/Services/Management/Management';
export { default as Personnel } from '../components/Services/Personnel/Personnel';
export { default as OurGoal } from '../components/Home/OurGoal';
export { default as AboutFounder } from '../components/Home/AboutFounder';
export { default as AboutCompany } from '../components/Home/AboutCompany';
export { default as ExpertAdvice } from '../page/Sections/ExpertAdvice/ExpertAdvice';
export { default as ExpertAdvice } from '../page/Sections/ExpertAdvice/ExpertAdvice';
